project_id = "udjdbdrngaslstlslplm"

[functions.betting-insights]
verify_jwt = false

[functions.edgeguide-run]
verify_jwt = false

[functions.edgeguide-latest]
verify_jwt = false

[functions.admin-trigger-run]
verify_jwt = false

[functions.run-edgeguide]
verify_jwt = false
